apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - name: stork
          image: wordpress:latest
          volumeMounts:
            - mountPath: /var/www/html
              name: wp-px-storage
